### ISSUE TITLE
Failed to Authenticate with email, Twitter on www.downes.ca

### ISSUE THREAD

**Issue by Downes** [aaronpk/indielogin.com#21] opened 2018-10-24 23:27 UTC
The Twitter error message was:  "Your Twitter profile linked to https://www.downes.ca/ but we were expecting to see https://www.downes.ca/. Make sure you link to https://www.downes.ca/ in your Twitter profile." Not sure what more I could have done.

Trying to login using email gives me "Invalid session state..

    login
    logout
    validate"
with the URL https://sso.indieweb.org/auth?code=91b3cb15a7c5f6fee4df1d1305e56a0f780af20d6ea937f803a1084fcad21800&state=jU1Xn9v0c18108aWWXaplYZRKbYrjPULtdD2qnAeXM0%3D

Using Firefox Quantum 63.0 (64-bit) on Windows 10 64-bit.

**Comment by aaronpk** [comment] 2019-02-18 16:55
Invalid session state sounds like maybe a cookie is being blocked. Do you have any extensions enabled that would block cookies?

**Comment by aaronpk** [comment] 2019-11-02 19:39
This is either an error with cookies being blocked, or is a duplicate of #16, so I'm going to close it.

**Closed by aaronpk** 2019-11-02 19:39 UTC
